# Generated by Django 6.0.6 on 2026-06-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('b2c_student', 'B2C Student'), ('b2b_student', 'B2B Student'), ('college_admin', 'College Admin'), ('super_admin', 'Super Admin')], default='b2c_student', max_length=20),
        ),
    ]
