# Generated by Django 5.2.4 on 2026-06-08 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_word_rate', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('express_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('editing_suggestions_fee', models.DecimalField(decimal_places=2, default=299.0, max_digits=10)),
                ('referral_credit', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('word_count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Processing', 'Processing'), ('Report Ready', 'Report Ready')], default='Submitted', max_length=50)),
                ('is_express', models.BooleanField(default=False)),
                ('has_editing_suggestions', models.BooleanField(default=False)),
                ('is_b2b', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('report_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='colleges.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
